sudo: required
services: 
    - docker
    
before_install: 
    -   docker build -t gauri/docker-react -f Dockerfile.dev .
    
script: 
    - docker run gauri/docker-react npm run test -- --coverage